"use client";

import { useState, useEffect } from "react";

export default function ImageGeneratorPage() {
  const [stock, setStock] = useState("");
  const [websites, setWebsites] = useState([]);
  const [selectedWebsite, setSelectedWebsite] = useState("");
  const [images, setImages] = useState([]);
  const [selectedImages, setSelectedImages] = useState([]);
  const [collageUrl, setCollageUrl] = useState(null);
  const [status, setStatus] = useState("");

  // Load saved websites
  useEffect(() => {
    const load = async () => {
      const res = await fetch("/api/social/get-websites");
      const data = await res.json();
      setWebsites(data.websites || []);
    };
    load();
  }, []);

  // Scrape images from website vehicle page
  const scrapeImages = async () => {
    if (!stock.trim() || !selectedWebsite) return;

    setStatus("Scraping images…");

    const vehicleUrl = `${selectedWebsite}/used-${stock}`;
    
    const res = await fetch("/api/scrape", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ url: vehicleUrl }),
    });

    const data = await res.json();

    if (!data.images) {
      setStatus("No images found.");
      return;
    }

    setImages(data.images);
    setSelectedImages([]);
    setStatus("");
  };

  // Toggle select/deselect image
  const toggleSelect = (url) => {
    setSelectedImages((prev) =>
      prev.includes(url)
        ? prev.filter((i) => i !== url)
        : prev.length < 4
        ? [...prev, url]
        : prev
    );
  };

  // Generate collage via API
  const generateCollage = async () => {
    if (selectedImages.length !== 4) {
      setStatus("Select exactly 4 images.");
      return;
    }

    setStatus("Generating collage…");

    const res = await fetch("/api/collage", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        imageUrls: selectedImages,
        ribbonText: "Generated by AI",
      }),
    });

    if (!res.ok) {
      setStatus("Error creating collage.");
      return;
    }

    const blob = await res.blob();
    const url = URL.createObjectURL(blob);
    setCollageUrl(url);
    setStatus("");
  };

  return (
    <div>
      <h1 className="text-2xl font-semibold mb-6">Social Image Generator</h1>

      {/* INPUTS */}
      <div className="space-y-4 max-w-xl">
        <input
          type="text"
          className="w-full p-3 border rounded"
          placeholder="Enter stock number or last 8 of VIN…"
          value={stock}
          onChange={(e) => setStock(e.target.value)}
        />

        <select
          className="w-full p-3 border rounded"
          value={selectedWebsite}
          onChange={(e) => setSelectedWebsite(e.target.value)}
        >
          <option value="">Select dealership website…</option>
          {websites.map((w, idx) => (
            <option key={idx} value={w.url}>
              {w.url}
            </option>
          ))}
        </select>

        <button
          onClick={scrapeImages}
          className="bg-blue-600 text-white py-3 px-6 rounded hover:bg-blue-700 transition"
        >
          Scrape Images
        </button>

        <p>{status}</p>
      </div>

      {/* IMAGE GRID */}
      {images.length > 0 && (
        <div className="grid grid-cols-4 gap-4 mt-6">
          {images.map((url, idx) => (
            <div
              key={idx}
              className={`border rounded overflow-hidden cursor-pointer ${
                selectedImages.includes(url) ? "ring-4 ring-blue-500" : ""
              }`}
              onClick={() => toggleSelect(url)}
            >
              <img src={url} alt="" className="w-full h-32 object-cover" />
            </div>
          ))}
        </div>
      )}

      {/* GENERATE COLLAGE */}
      {selectedImages.length === 4 && (
        <button
          onClick={generateCollage}
          className="mt-6 bg-green-600 text-white py-3 px-6 rounded hover:bg-green-700 transition"
        >
          Generate Collage
        </button>
      )}

      {/* OUTPUT */}
      {collageUrl && (
        <div className="mt-6">
          <h2 className="text-xl font-semibold mb-2">Final Image</h2>
          <img src={collageUrl} className="w-[850px] h-[850px] border rounded shadow" />
          <a
            href={collageUrl}
            download={`collage-${stock}.jpg`}
            className="block mt-4 text-blue-600 underline"
          >
            Download JPEG
          </a>
        </div>
      )}
    </div>
  );
}
